<!--DO NOT HANDEDIT THIS - AUTOMATICALLY GENERATED BY LIB.SH-->
<?php require('../header.php');?><p>If you think you have a copy of one of our publications that isn't present here please get in contact, e-mail address is on the left. Like everything else on this website all this material is under a <a href="http://creativecommons.org/licenses/by/2.0/uk/">Creative Commons licence.</a></p>

<?php begintextbox("The Journal of London University Caving Clubs [LUCC]");?>
<center>
<h2>The Journal of London University Caving Clubs [LUCC]</h2><h3>Chelsea College Caving Club [CCCC]</h3><h3>Imperial College Caving Club</h3><h3>Queen Mary College Caving Society [QMCCS]</h3><h3>University College London Speleological Society [UCLSS]</h3>
</center>
<p>
<i>"... the three University Club's histories are very closely inter-related and now the journal should ensure that this pattern of beneficial co-operation will continue. It is hoped that it will even stimulate some people to do some caving with a purpose - certainly far more rewarding than the old tourist trips. A mere write up of the log book has very limited interest, while an entirely scientific publication is beyond the scope of the clubs, so this journal is attempting to strike a happy medium."</i> <b>Tony Waltham, LUCC 1 Editorial, December 1966</b></p>
<p>Alas, we are the sole surviving member of the LUCC collective. We are intending to have a (complete as possible - we believe there were 14 in the series, Dec '66 - June '73) set of LUCC journals freely downloadable here as PDFs, in testament to the achievements of the now defunct clubs and as a record of original exploration both within the country and abroad. If you have LUCC #1,2,3 or 11 we would be most interested in talking to you, as they haven't been spotted in the wild since 2000!</p>
<p>A summary of the contents of the LUCC journals can be garnered from the first half of our <a href="http://www.union.ic.ac.uk/caving/lib/25yr_history.pdf">25 Yr History of the Club (1987) [12mb PDF]</a> (<a href="/caving/wiki/index.php?n=Main.TheFirst25Years">Type up in progress on Wiki...</a>).</p>
<?php endtextbox();?>

