echo "<!--DO NOT HANDEDIT THIS - AUTOMATICALLY GENERATED BY LIB.SH-->"
echo "<?php require('../header.php');?><h2>Newsletters</h2><p>This is a repository of the the newsletters that the ICCC has produced over it's history. If you think you have a copy of one of our publications that isn't present here please get in contact, e-mail address is on the left. Like everything else on this website all this material is under a <a href="http://creativecommons.org/licenses/by/2.0/uk/">Creative Commons licence.</a></p>"

for i in *.pdf
do

 echo "<?php begintextdatebox(\"\",\"${i}\");?>"
 echo "<table border=\"0\"><tr><td>"
echo -n "<a href=\"/caving/lib/"
 echo -n "${i}\">"

#convert "${i}[0]" -resize 150 "${i}.jpg"
 echo -n "<img align=left src=\"${i}.jpg\"></a>"
echo "</td><td>"
 
echo -n "<p><a href=\"/caving/lib/"
 echo -n "${i}\">${i}</a>" #Add Link to filename of PDF
echo "<pre>"
cat "${i}.con" #spurt out text file (.con) of table of contents
echo "</pre></p>"
echo "</td></tr></table>"
echo "<?php endtextdatebox();?>"
 echo

done

echo "<?php require('../footer.php');?>"
