<!--DO NOT HANDEDIT THIS - AUTOMATICALLY GENERATED BY LIB.SH-->
<?php require('../header.php');?><h2>Newsletters</h2><p>This is a repository of the the newsletters that the ICCC has produced over it's history. If you think you have a copy of one of our publications that isn't present here please get in contact, e-mail address is on the left. Like everything else on this website all this material is under a <a href=http://creativecommons.org/licenses/by/2.0/uk/>Creative Commons licence.</a></p>
<?php begintextdatebox("","25yr_history.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/25yr_history.pdf"><img align=left src="25yr_history.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/25yr_history.pdf"</a><pre>
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-01-October-1983.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-01-October-1983.pdf"><img align=left src="ICCC-01-October-1983.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-01-October-1983.pdf"</a><pre>
President's Piece
I.C.C.C. goes to France
Easterwater - A 'Banging' Trip to the New Extension
The Gear Column
 - Underground Clothing
 - Light-Weight Lunacy
 - Alternative Caving Lamps
Debbie's Tit-Bits
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-02-January-1984.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-02-January-1984.pdf"><img align=left src="ICCC-02-January-1984.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-02-January-1984.pdf"</a><pre>
1984 Spring Term Cavig Meets
Caving Trip Reports
 - Derbyshire 4-6 Nov. 1983
 - Yorkshire 18-20 Nov. 1983
 - South Wales 2-4 Dec. 1983
The Gear Column
 - Ladders and Lifelines
 - Fractionement et Deviation 
Viewpoint
Debbie's Tit-Bits
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-03-May-1984.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-03-May-1984.pdf"><img align=left src="ICCC-03-May-1984.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-03-May-1984.pdf"</a><pre>
1984 Summer Term Caving Meets
Caving Trip Reports
 - Mendip 13-15 Jan. 1984
 - Yorkshire 26-28 Jan. 1984
 - South Wales 10-12 Feb. 1984
 - Derbyshire 24-26 Feb. 1984
 - Yorkshire 9-11 Mar. 1984
The Gear Column
 - 'Noeuds Amortisseurs'
 - Useful knots to know
"That would make a good picture"
Cavernas del Peru
"It looks a bit desperate"
Debbie's Tit-bits
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-04-January-1985.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-04-January-1985.pdf"><img align=left src="ICCC-04-January-1985.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-04-January-1985.pdf"</a><pre>
No contents in original:
1985 Spring Term Caving Meets
Editorial: ICCC Meets / Expedition Policy 1985 Onwards
Caving Trip Reports
 - Mendip Otter Hole 22-24 Jun. 1984
Solo Caving - The Little Neath Incident
Underground Survival
And Outwards Bound Summer
Re-Belays - How to pass them
The Red Bolts
News...News...News...
Guidlines for cliquey trips
Character Assasination Supplement
Cartoon
Cave Wars Part 1
Cave Wars Part 2
Caving Crossword
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-05-April-1985.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-05-April-1985.pdf"><img align=left src="ICCC-05-April-1985.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-05-April-1985.pdf"</a><pre>
Committee & Activities
Stop Press: French Tour 1985
A Hundred Years of Caving
Letters to the Editor
Singularly Ropey Technique
More Letters
Whernside - A Comment
Meets List 1985/1986
Who should be next year's President?
Pre-election BRiefing
Yer Actual Welsh
Crossword Solution
Cartoons
Cave Wars Part 3
Cavers Wordsearch (completed)
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-06-October-1985.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-06-October-1985.pdf"><img align=left src="ICCC-06-October-1985.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-06-October-1985.pdf"</a><pre>
Committee and 1985/1986 Meets List
Editorial
News
Letters
 - Expedition Policy
 - CRO Donation Thankyou
 - Whernside Closure
General
 - Not the Boys from Brazil (Peru Expo)
 - Cave Instructor Training Course (Whernside)
 - South Pembrokeshire - England's Second Major Caving Area
 - Debolting
 - A History of Vertical Caving
 - 'Bear Rug' Cartoon
Technical
 - Caving Ropes
 - The Caving Sit-Harness
Review
 - The National Caving Conferance 21 Sept. 1985
The Caveway Code
Caving Crossword
Back-Stabbing Supplement
 - Cave Wars Part 4
 - Mendips Caving
 - Quote Competition
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-07-November-1986.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-07-November-1986.pdf"><img align=left src="ICCC-07-November-1986.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-07-November-1986.pdf"</a><pre>
Committee and 1986-1987 Meets List
Editorial
Expedition Extravaganza
 - Italy Summer 1987
 - Cananda Expedition 1986
 - Update on Peru
 - Operation Raleigh PHase 4B Souther Chile
    A personal Report by UK Venturer Debbie Armstrong
Cavers Echoes
 - REPTILE Dodgi-Guides Ltd; A Holiday with a difference!
 - REPTILE GUIDEs - Exodus Expeditions Trekking
 - 'Fixed aids in Caves'; Point for Reflection
A History of Underground Lighting
Caverns Measureless to Man (Survey Problems)
 - 'Longueur? - Hargn!' Cartoon
Back-Stabbing Section
 - Speleo Speal
 - Cave Warts Part 5
Letters to the Editor
 - Return to the Harrison Values?
 - A Worried Caver Writes
Caving Acrostic
Crossword Solution
Tackle-Bag Cartoon
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-08-June-1987.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-08-June-1987.pdf"><img align=left src="ICCC-08-June-1987.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-08-June-1987.pdf"</a><pre>
Committee & 1987/8 Meets List
Editorial
The Real Cave Wars
Cave Photography - A Simple Guide
Modern Vertical Technique
Imperial College Caving Club - The First 25 Years Part 1
 - Rumbling Hole Survey (1968)
 - Trou D'anaffed, Taza Maroc Survey (1971)
 - Lost Johns' Maypole Passage Extension Survey (1972)
Cave Wars - Part 6
Caving Crossword
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-09-Spring-1988.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-09-Spring-1988.pdf"><img align=left src="ICCC-09-Spring-1988.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-09-Spring-1988.pdf"</a><pre>
Committee 1987/8
Editorial
President's Report 1987-88
Tickbox President's Report
Imperial College Caving Club - The First 25 Years Part 2
 - Morocco Surveys (1979)
 - Photo of Tripa Tis Nifis, Astraka, Greece
 - La Sima de Iraca, Ninabama, Peru Survey (1984)
 - Daily Telegraph June 12 1986 Clipping
Summer Tour '88
Caving in the Apuan Alps of Northern Italy
 - Antro del Corchia
 - Complesso Figiera-Farolfi-Corchia Location Map
Caverns, Chasms, Hollows & Holes
The Hydrologo of the Uchkupisjo River Cave, Ninabamba, Peru
 - The Prospects for further exploration
 - Introduction
 - History of Exploration
 - Comparison of Hydrological Observations
 - Conclusions
Cave Wars - Part 7
Cryptic Caving Crossword
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-10-Winter-1988.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-10-Winter-1988.pdf"><img align=left src="ICCC-10-Winter-1988.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-10-Winter-1988.pdf"</a><pre>
Committee 1988-1989
Editorial
President's Piece
Summer Tour '89
Ropewalking
Spain 88
South East Cave Rescue Organisation
A cautionary 'tail
Much Ado about Nothing
 - A supplement to the 'History of Underground Lighting' Issue 7
Leonardo da Vinci: Inventor of the multi-scender?
So That's the Reason you go caving!!?
Problems
OLM Enterprises Present
 - Episode 1: The Great Caving Adventure
Answers to 'Caverns, Chasms, Hollows & Holes' Issue 9
Caving Crossword
Caving Supplies Ltd. (Spoof) Advert
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-11-Spring-1989.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-11-Spring-1989.pdf"><img align=left src="ICCC-11-Spring-1989.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-11-Spring-1989.pdf"</a><pre>
Editorial & President's Bit
 - A Fresher's Eye View of IC3
Annual Report
Summer Tour
Elections
A Name - What's in a Name?
 - Various Cave Entrance Photos
 - Beachy Head Cave, Eastbournce, Survey 
Solution to crossword Issue 10
Nylon Highway (A Critical Review)
Caverns, Chasms, Hollows & Holes
OLM Enterprises Present
 - Episode 2: The Darkness Beckons
Problems
For Sale
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-12-December-1989.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-12-December-1989.pdf"><img align=left src="ICCC-12-December-1989.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-12-December-1989.pdf"</a><pre>
Editorial
Speleology (But Mostly Other Things) in Sunny South Africa
Caving in America
So What Happened Anyway?
 - The Truth About Bullpot.
 - Photos of the Rescue
 - Rescue Rigging Guide (Bullpot)
A Name - What's in a Name? Part 2
Winter Alpine Caving
 - Reseau Jean Bernard Survey
Answers for Issue 11
Problems
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-13-Spring-1990.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-13-Spring-1990.pdf"><img align=left src="ICCC-13-Spring-1990.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-13-Spring-1990.pdf"</a><pre>
Editorial
President's Report
Dave's Piece
'89 Summer Tour in the Vercors, France
'89 Summer Tour to the Vercors - Part II
 - Into the Lair of the Damned
 - Antre Des Damnes Survey
The Czech Visit, August 1989
Christmas Visit to the Jura 1990
 - Gouffre de Gros-Gadeau Survey
 - Baume des Cretes Survey
 - Gouffre du Paradis Survey
 - Reseau du Verneau Survey
The Library
The Italian Contact
In Search of the Long Formations of Wookey
Caverns, Chasms, Hollows & Holes
The Duties of Club's Officers
Answers for Issue 12
Brits on the Piss Tour '89 (or, The Last Great Caving Adventure)

</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-14-Winter-1990.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-14-Winter-1990.pdf"><img align=left src="ICCC-14-Winter-1990.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-14-Winter-1990.pdf"</a><pre>
Editorial
President's Piece
Letters
 - IC3 Through the Eyes of a Fresher
 - First Impression of IC3
 - The Concerns of the Old Lags
Summer Tour '90 - The Alternative Expedition
 - Reseau de la Den de Crolles (Survey)
Cuevas y Habichuellas (Dominican Republic)
 Or: What I did in the summer holidays
Strange but True
A Name - What's in a Name? Part 3
A Few Rules about Using Club Gear
Why Knot? - Why Not
Story Time - A Night in the Cave
Hanging Around London in the Summer!
Caving Crossword / Word Fit
Answers for Issue 11
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-15-Summer-1991.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-15-Summer-1991.pdf"><img align=left src="ICCC-15-Summer-1991.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-15-Summer-1991.pdf"</a><pre>
Editorial
Rob's Bit
Letters
Easter Visit to France
 - Reseau Bel Espoir_Diau Survey
 - Reseau du Verneau Survey
Fermanagh - N. Ireland Christmas Tour 1990
 - Area Map
Radon in British Caves
Dangling on a Silken Web of Steel 
A Name - What's in a Name? Part 4
Cave Formations
 - Chemistry
 - Stalagmites and Stalactites
 - Curatins and Draperies
 - Helectites
 - Flowstone
 - Rimstone Pools
Chasms, Caverns, Hollows and Holes
Caving Crossword / Word Fit
Now and Then
Members' Addresses
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-16-Spring-1992.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-16-Spring-1992.pdf"><img align=left src="ICCC-16-Spring-1992.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-16-Spring-1992.pdf"</a><pre>
Bron's Burble
Gear Review: Malham Carbide Generator
Classic Caving on Monte Canin
Slovenia 1991
Postojna: 170 Years of Tourism
Under Durres: A Reconnaissance of Albania
Deep Throat!
Classic Caving: Operation -1000
Soviet Descender Designs
ICCC Tours & Expeditions
Rough Guide to the History of Caving
Story Time: Goodbye Cruel World
Puzzled?!?
Make Your Own Stalactites
Now and Then
Cover: Visitors to Postojna Jama in 1896

</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-17-Spring-1993.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-17-Spring-1993.pdf"><img align=left src="ICCC-17-Spring-1993.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-17-Spring-1993.pdf"</a><pre>
Tim's Bit
Deep in the South of France
Noises in the Deep
Belgium '92 - The Trou Story
Shock Treatment!
The Caves of Easter Island
Hot Stuff!!
Speleo Statistics
Cavers Measureless to Man
The Upper Crust
South-East Cave Rescue Organisation
Hooked on Heavy Metal?
Seeing the Error of their Ways
Story Time: A Wild Stab in the Dark
Quote - Unquote
Mountains of Rubbish
Chasms, Caverns, Hollows & Holes
Ten Little Cavers
Magic Mushrooms
Now & Then
Cover: In Close to the Edge of the Road, 
Vancouver Island, by Linda Heslop. 
From Nylon Highway (USA) 34 (1991).
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-19-Winter-1995.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-19-Winter-1995.pdf"><img align=left src="ICCC-19-Winter-1995.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-19-Winter-1995.pdf"</a><pre>
Mark's Missive
Meets List 1995
ICCC Tours & Expeditions
Jurassic Lark
Slovenian Reccy
Speleo-Statistics
"The Cave was Surveyed"
Dear Diary
A flapjack too far
Brain Drain
More Bullshit
Blind but not Bland
Gaping Gill - the really sporting way
Forest of Dean Cavers' Fair 1994
Otter Hole
Carbine Connections
Cavers, Chasms, Hollows & Holes
Over Exposed?!?
Renassance Rope Techniques
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","ICCC-20-Spring-1996.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/ICCC-20-Spring-1996.pdf"><img align=left src="ICCC-20-Spring-1996.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/ICCC-20-Spring-1996.pdf"</a><pre>
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php begintextdatebox("","LUCC-12-Winter-1971.pdf");?>
<table border="0"><tr><td>
<a href="/caving/lib/LUCC-12-Winter-1971.pdf"><img align=left src="LUCC-12-Winter-1971.pdf.jpg"></a></td><td>
<p><a href="/caving/lib/LUCC-12-Winter-1971.pdf"</a><pre>
</pre></p>
</td></tr></table>
<?php endtextdatebox();?>

<?php require('../footer.php');?>
