<? require('../header.php'); ?>

<h1>Yorkshire</h1>

<h2>Weekend Trip 21&ndash;23 March 2014</h2>
<h2><a href="/caving/photo_archive/trips/2014-03-21%20-%20yorkshire/">Photos</a></h2>
<center><a href="/caving/photo_archive/trips/2014-03-21%20-%20yorkshire/"><img width=800 src="/caving/photo_archive/trips/2014-03-21%20-%20yorkshire/RhysTyers-DSC_0092--orig.jpg"></a></center>

<h3>Rhys, Jack, Fiona, Sam, Sarah, Dave KP, DW, Andy, Jarv, Dani</h3>
<h2>Friday</h2>
<p>What began as a small trip became a tiny trip as many an uncommitted caver succumbed to apathy, exams and other unreasonable excuses. The crack team was composed of myself, Sam, Fiona, Sarah, Jack and Dave. Thanks to this lightweight load out we were trundling away from South Ken by 7pm and continued to make record time all the way to the NPC, arriving to find DW (and sleeping Jarv and Dani) waiting for us at the civilised hour of 12.30am.</p>

<p style="text-align:right"> Rhys</p>

<h2>Saturday</h2>
<h3>Easegill</h3>
<h3>Pip -> Mistral: Rhys, Sam, Sarah, Jack and Dave KP</h3>
<h3>Mistral -> Mistral: Fiona, Andy</h3>
<p>Jack and I woke up first on Saturday, both agreeing that due to the early arrival we'd managed to get a full 8 hours. A mushroom biased breakfast soon roused the rest of the team and we spent the usually 3 hours faffing and deciding what cave to do. I initially wanted to shove Jack into Peterson's (and subsequent Roly Poly passage) to see what would happen to his knees  (bend or break?) but was advised that a Pip trip would probably be introduction enough to the delights of full contact sideways squeezing. If I had been in Pip before I couldn't remember and had little idea of what to expect.</p>
<p>Full of tea and enthusiasm (same thing?) we set off down Pip. It turned out to be an expectationally worthwhile trip and I think one of my favourite entrances to do down (up might not be so fun). Each squeeze is just the right combination of disturbingly committing and swiftly over to be very fun.</p>
<p>We regularly consulted the description we had with us but it became quickly obvious what it was going to say. Constricted/crawl squeeze to awkward pitch head, repeat. One of the more entertaining pitch heads included popping out directly over the pitch and if going feet first as we all did involved flailing your feet around until you found that iron bar that you had to perch on, parrot like, as you rigged your descender. Or you could do as Dave did and sit with legs either side of the bar and spend 10 minutes desperately attempting the splits to get off it. An excellent thrutchy traverse follows (IIRC) and I think everyone thoroughly enjoyed finding out that pretty much any body part can be used as a point of contact. The traverse ends in a pretty stal decorated chamber and we had a break and photo sesh before continuing.</p>
<p>Eventually reaching XXX chamber we had a discussion over how to exit. Our original plan had been to go out via Link which Andy had kindly volunteered to rig for us. The alternative was Mistral. We read the description for each and noticing that Link had frequent use of the words "cobbly", "muddy", "wet", "crawl" and Mistral had frequent use of the words "20", "minutes", "away", we opted for a swift exit through Mistral. True enough, 20 minutes later we were scrambling up the loose cobble entrance onto the Easegill beck. Whilst the others rested I ambled 2 minutes up stream to derig Link, no more difficult than pulling the rope from the surface. I was quite surprised to find no rope when I got there.  I explained this to the rest of the team but no one could think of a reasonable explanation, surely Andy wouldn't attempt to play such a cruel trick. </p>
<p>Back at the bus we interrogated Andy, who had exited with Fiona a little before us, who made up some bollocks about "hearing us coming out of Mistral". He can probably be forgiven as he had reclaimed one of our Northern Caves books from the pocket of a passing caver who, upon presumably finding the book at a hut some time before, had been unable to tell if the large ICCC labels meant the International Christian Chamber of Commerce or us and so had kept the book without attempting to return it.</p>

<p style="text-align:right"> Rhys</p>

<p>With only six people in the van, the drive up was very quick, and got into the NPC at 1am. The next morning, we said hello to Jarv, Dani and Andy, and then split into three groups - Jarv and Dani into some Easegill pot, Fiona and Andy down Mistral, and Rhys, Dave KP, Sam, Sarah and myself in Pippikin, with the intention of exiting out of Link, which Andy was to rig for us.</p>
<p>I don't have many pictures from Pippikin. I found it a bit traumatic - tight, sideways squeezes feet first into the abyss, grunting and cursing every metal object clipped to my harness, my camera in my chest pocket, my helmet stuck at one angle. By the nastiest squeeze out onto a small metal scaffolding tube lodged into a crack, I'd really lost it. I crawled in backwards, and then Dave told me to wait as he wasn't ready yet. Lodged there, unable to relax unless I slid down and got stuck in the crack. Then I heard Rhys singing 'Country Roads' from the bottom, and joined in, temporarily forgetting my predicament. After backing out and down the rope, I felt like I could take on anything, and I was singing most of the way out of the cave.</p>
<p>In the end, we decided not to exit via Link, but take the easier exit from Mistral. This was just as well, as Andy decided to de-rig Link so we would have had to crawl through mud and streamways only to have to return the same way. Thanks Andy. Thandy.</p>
<p>We returned to the NPC, cooked an enormous aubergine and okra balti curry, and sat around exaggerating our exploits. </p>
<p style="text-align:right"> Jack</p>

<h2>Sunday</h2>

<h3>Alum Pot: Rhys, Jack, DW</h3>
<p>Finding that just Jack and I wanted to go caving on Sunday morning (i.e. being the only ones awake) we swiftly cooked breakfast and corralled DW into an Alum trip. I vaguely remembered DW and Jan going to Alum in my first year and the photos Jan took made it look like a truly spectacular place and wanted to see it for myself.</p>
<p>Alum is ideally located 10 minutes from the parking spot (most important feature any cave can have), just a gentle walk up a picturesque stream valley. The shaft begins at the surface and is as impressive as the photos made it look. Two streams tumble down from the top at either end and trees perch at various precarious angles all around. We walked further up the hill, dropping into a streamway and following it underground, past a small group clad in neoprene and onwards to the first pitch. Jack rigged, with the neopreners arriving in time to heckle him. Down the first pitch the passage opens out into the side of the main Alum shaft, directly behind one of the waterfalls. I took JAck's camera at this point and did my best to fill the sd card with as many overexposed pictures of the cave as I could. Who knew taking pictures in a well lit environment would be so difficult, give me complete darkness and a dodgy flash unit any day. Jack rigged another pitch down to a traversable ledge where I took over and crossed the large boulder wedged in the centre of the shaft to get to the last hang. </p>
<p>At the bottom, now quite shaded from the day light, the waterfalls combine into an impressive stream and it's suddenly much colder. DW dropped in soon after me and pointed out the final 10 metre pitch that we could have gone down if I hadn't forgotten to pack the rope. We headed out almost as soon as we got to the bottom, keen to get back into the warmer, better lit cave above. Unusually I managed to avoid any derigging with both DW and Jack doing a tackle sack each.</p>
<p>On the surface we bimbled over to another couple holes further up the hill and dropped in briefly, DW leading us on a few entertaining loops through the twisting streamways and crawls that proved to be a nice warmdown.</p>
<p style="text-align:right">Rhys</p>
<p>The next day I woke up early, and Rhys and I realised we were probably the only people who wanted to go caving. We roped in Dave W and headed to check out Alum - the only thing I knew about the cave was that a couple had recently drowned there.</p>
<p>Alum is a huge shaft into the ground, with sunlight all the way to the bottom with waterfalls cascading in from all sides. We entered via another hole about 50 m away, and worked out way underground to opening half way down the shaft. I rigged the first two ropes, first a simple descent, and then a traverse in the sunshine, followed by a short descent down. Rhys took over and handed me back my camera, and I started taking a lot of photos. A huge boulder is lodged between two walls of the shaft, and we crossed over it on the rope to continue our descent to the bottom. It was extremely wet and quite a bit darker down there, so Dave W took off up as soon as I'd gotten off the rope, leaving me to de-rig. It was a short trip, but the light was beautiful, the SRT was easy and the cave was just gorgeous</p>
<p style="text-align:right"> Jack</p>
<? require('../footer.php'); ?>
